### ISSUE TITLE
The music is not silent after death 

### ISSUE THREAD

**Issue by xxfast** [xxfast/JetPackSavesThePlanet#100]
**Steps to replicate;** After game over, the music doesn't fade out

**Issue;** Cosmetic

**Likely cause;** Possibly conflicting triggers from Oxygen

**Comment by 6819710** [comment]
Issue Identified as Merge Conflict, Player prefab not correctly updated in master, notably included Audio Systems, and settings in Health Scrip, OnDeath event handler

Identification took ~10min.

Note: Bug not exsistant in audio-reballancing branch.

**Comment by 6819710** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BUG #100: Music not falling silent of death.](https://trello.com/c/oNEGqCCW/42-bug-100-music-not-falling-silent-of-death)

**Comment by 6819710** [comment]
Fixed in pull #101
