### ISSUE TITLE
BUG: Noticeable pag on imput methof selection

### ISSUE THREAD

**Issue by 6819710** [xxfast/JetPackSavesThePlanet#108]
Wgen begining game wgoge lag on player imput. I know that this is to facilitate cross platform play but its big issue.

Bug type: lag

Suggested fix. Rather than waiting for input perhaps determine ans set input method based on platform detection? Ie. Game determines platform operating on and sets method based on that result.

**Comment by xxfast** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Fix #; Input Overhaul](https://trello.com/c/IEf9fuAe/44-bug-fix-input-overhaul)
