### ISSUE TITLE
BUG - Player Destroying Self on play

### ISSUE THREAD

**Issue by 6819710** [xxfast/JetPackSavesThePlanet#15]
Player seems to be taring itself apart on the basic play of level 1, needs to be assessed and fixed

**Comment by 6819710** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BUG - Player Destroying Self on play](https://trello.com/c/FzpKdsmG/20-bug-player-destroying-self-on-play)

**Comment by xxfast** [comment]
fixed in  #13
