### ISSUE TITLE
Player dying in the Menu State

### ISSUE THREAD

**Issue by xxfast** [xxfast/JetPackSavesThePlanet#90]
Steps to replicate; Do nothing in the menu, the player will start to suffocate

Issue; Gameplay

Likely cause; No triggers that disable the player's breaking behaviour. This can be easily fixed by attaching the trigger to the UnityEvent onMenu of the state manager

**Comment by 6819710** [comment]
note: on testing of 17w40 player seems to be active from launch, issue is with state manage
recommendation, start with state diagram noting what should be active in each state
then rework code implementing changes noted in diagram.

ensure diagram is active document and update documentation of changes made to settings.
